### ISSUE TITLE
Doesn't work in javascript files

### ISSUE THREAD

**Issue by Lazk3r** [0x100101/lab.nvim#10]
When I try to run `:Lab code run` in a javascirpt file I'm getting this error:
![image](https://user-images.githubusercontent.com/82919717/193723960-1b7ced53-0623-4d7b-a71f-3f76e4db98f4.png)
OS: Arch Linux
Neovim: 0.8.0

**Comment by 0x100101** [comment]
Hi @Lazk3r. Please double check you have node 16.10+ and that the post install hook `cd js && npm ci` is configured and executing correctly. (More detail in README). Those are the most likely culprits.
