### ISSUE TITLE
Troubleshooting "CodeRunner is currently disabled"

### ISSUE THREAD

**Issue by MatthewCushing** [0x100101/lab.nvim#12]
Hey, amazing looking extension!  I'm super excited to get using it.  However, I've been running into the error `CodeRunner is currently disabled` whenever I try to run `:Lab code run`, `:Lab code stop`, `:Lab code panel`, or `:Lab code config`.  I've looked into the source code and saw that this occurs when the CodeRunner's state is set to `true`.  I'm not the best at working backwards with Lua code like I am with JS/TS to find everything that would change the state.  I'm running Packer and literally just copy/pasted your minimal example in the ReadMe into my Packer config

```lua
use { '0x100101/lab.nvim', run = 'cd js && npm ci', requires = { 'nvim-lua/plenary.nvim' } }
```

I also added the completion source in my `cmp.nvim` setup.

I'm running Node v16.16.0.  `>= v16.10.0` is the plugin's requirement, so I think I'm good there; although I could try running v16.10.0 to make sure nothing odd is happening with the newer version.  

I went ahead and manually installed the JS deps inside the js folder in the plugins directory at `~/.local/share/nvim/site/pack/packer/start/lab.nvim` just in case Packer's `run` option wasn't working right for some reason.

I tried manually enabling CodeRunner in the setup of the plugin even though it's the default.

As far as I can tell I've done everything correctly.  Am I missing something? Anything you might be able to point me out to? 
 Oh, and I'm on a Macbook Pro M1 Max running on MacOS Ventura 13.1, if that changes anything.

**Comment by MatthewCushing** [comment]
I guess calling the setup function is required.  Might be worth adding that to the docs where you put the packer example like so:

```lua
use { '0x100101/lab.nvim', 
  run = 'cd js && npm ci', 
  requires = { 'nvim-lua/plenary.nvim', 
  config = function()
    require('lab').setup({})
  end
} }
```

Now I've got it working, but running into an issue where I get this error every time `Lab code run` is ran
```
Error executing vim.schedule lua callback: ...site/pack/packer/start/lab.nvim/lua/lab/virtual_text.lua:72: line value outside range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...site/pack/packer/start/lab.nvim/lua/lab/virtual_text.lua:72: in function 'render'
        .../site/pack/packer/start/lab.nvim/lua/lab/code_runner.lua:228: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by 0x100101** [comment]
@MatthewCushing Happy you got that sorted out! I'm going to update the `CodeRunner is currently disabled` message to `The code runner is currently disabled. If this is unexpected, check that lab.setup is being called in your config.`

I'll leave the docs as-is for now. The way you called setup -- as part of the packer command -- works, but there are a bunch of other ways you might do it too. I don't want to be overly opinionated. The setup call is documented under the packer example too.

If you're still having issues with the `nvim_buf_set_extmark` error can you pls set up a new issue with repro code. Thanks!
