### ISSUE TITLE
Cannot find dist/index.js

### ISSUE THREAD

**Issue by ChristianChiarulli** [0x100101/lab.nvim#7]
![image](https://user-images.githubusercontent.com/29136904/185723963-db64c42b-ff20-41ca-b126-8c59c8d91e0c.png)

tested with node 16.10.0 and 17.9.1

**Comment by 0x100101** [comment]
@ChristianChiarulli thanks for reporting this. My bad, I released some changes today without being careful enough. If you update to v0.2.5 you should be all good.

**Comment by ChristianChiarulli** [comment]
@0x100101 that fixed it, thanks.
