### ISSUE TITLE
Command not working? stderr nil nil

### ISSUE THREAD

**Issue by jugarpeupv** [0x100101/lab.nvim#8]
Hello, 

First of all, thanks for this awesome idea, being able to use Quokka inside neovim is amazing. 

I'm trying to get it to work but i encounter this problem, when i start neovim i see in the console

<img width="234" alt="image" src="https://user-images.githubusercontent.com/69123204/187050061-a3c0199c-b71d-4a91-aef2-4ca49e250203.png">

Then when i run Lab code run, i see this output but nothing else happens

<img width="948" alt="image" src="https://user-images.githubusercontent.com/69123204/187050109-cedc8042-bdfc-4f2e-a33e-fb4aa70cbc2f.png">

Do you have any idea?

**Comment by jugarpeupv** [comment]
Hello again,

It is working now, i guess the post install process was not executed correctly when i first installed it

It is such an amazing plugin, many thanks!!

<img width="622" alt="image" src="https://user-images.githubusercontent.com/69123204/187070472-40f60adb-9ad4-4b30-a099-9bb0f0797757.png">

**Comment by 0x100101** [comment]
Hi @jugarpeupv,

That's great! Happy to hear you got it working. Soon I'll be adding a health check feature that will help diagnose issues with the plugin install/setup.

**Comment by stasgavrylov** [comment]
@jugarpeupv Hello, could you please explain how you've fixed this? I think I'm having the same issue, seeing only `Executing... Run ID: #XXXXX` in the lab panel :(
